### ISSUE TITLE
Unable to Reproduce Numerical Experiment Results

### ISSUE THREAD

**Issue by tsano430** [AdityaLab/pinnsformer#5]
Hello,

I am trying to reproduce the [numerical experiments](https://github.com/AdityaLab/pinnsformer/blob/main/demo/1d_reaction/1d_reaction_pinnsformer.ipynb) presented in the paper using the code provided in this repository, but I am unable to obtain the expected results. My environment and code are shown [here](https://gist.github.com/tsano430/656407faeac11a3ea7307d7f0d2c7772), which generates the following figure.

![1dreaction_pinnsformer_pred](https://github.com/user-attachments/assets/160b873c-5efe-4e3c-bc90-61a439f455bb)

The result differs significantly from that of  the paper. There are no error messages, but the outputs are not as expected. Could you please provide any insights on what might be causing this discrepancy? Thank you.

**Comment by tsano430** [comment]
When executed with different seeds, I was able to reproduce the results of the paper with several seeds. Considering that only the initialization part contains randomness, I believe that it may get stuck in a local minimum when the initial values are unfavorable.

**Comment by tsano430** [comment]
Switching from Adam to L-BFGS might help avoid this issue.

https://arxiv.org/abs/2402.01868

**Comment by luokuang2001** [comment]
I’ve been working on replicating the results from the paper and have made several attempts, including using different random seeds, starting with Adam followed by L-BFGS, and trying various initializations. However, I’ve still been unable to reproduce the results as described in the paper.

Could you kindly provide a working demo or share the specific code along with the hyperparameters used in your experiments?

My codes are as follows，

`#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import random
from torch.optim import LBFGS
from tqdm import tqdm
import scipy.io

from util import *
from pinn import PINNs
from pinnsformer import PINNsformer

# In[2]:

seed = 66
np.random.seed(seed)
random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)

# 检查是否有可用的 GPU
# torch.cuda.init()  # 初始化 CUDA 设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
if torch.cuda.is_available():
    gpu_name = torch.cuda.get_device_name(0)  # 获取第一个 GPU 的名称
    print(f"GPU name: {gpu_name}")
else:
    print("No GPU available.")

# In[3]:
#
N1 = 51
N2 = 51

step_len = 1e-4
NumStep = 5

# Train PINNsformer
res, b_left, b_right, b_upper, b_lower = get_data([0, 2 * np.pi], [0, 1], N1, N2)
res_test, _, _, _, _ = get_data([0, 2 * np.pi], [0, 1], 101, 101)

res = make_time_sequence(res, num_step=NumStep, step=step_len)
b_left = make_time_sequence(b_left, num_step=NumStep, step=step_len)
b_right = make_time_sequence(b_right, num_step=NumStep, step=step_len)
b_upper = make_time_sequence(b_upper, num_step=NumStep, step=step_len)
b_lower = make_time_sequence(b_lower, num_step=NumStep, step=step_len)

res = torch.tensor(res, dtype=torch.float32, requires_grad=True).to(device)
b_left = torch.tensor(b_left, dtype=torch.float32, requires_grad=True).to(device)
b_right = torch.tensor(b_right, dtype=torch.float32, requires_grad=True).to(device)
b_upper = torch.tensor(b_upper, dtype=torch.float32, requires_grad=True).to(device)
b_lower = torch.tensor(b_lower, dtype=torch.float32, requires_grad=True).to(device)

x_res, t_res = res[:, :, 0:1], res[:, :, 1:2]
x_left, t_left = b_left[:, :, 0:1], b_left[:, :, 1:2]
x_right, t_right = b_right[:, :, 0:1], b_right[:, :, 1:2]
x_upper, t_upper = b_upper[:, :, 0:1], b_upper[:, :, 1:2]
x_lower, t_lower = b_lower[:, :, 0:1], b_lower[:, :, 1:2]


def init_weights(m):
    if isinstance(m, nn.Linear):
        torch.nn.init.xavier_uniform_(m.weight)
        # torch.nn.init.normal_(m.weight, mean=0, std=0.1)
        m.bias.data.fill_(0.01)


# In[4]:


model = PINNsformer(d_out=1, d_hidden=512, d_model=32, N=1, heads=2).to(device)

model.apply(init_weights)
# optim = LBFGS(model.parameters(), line_search_fn='strong_wolfe')
optim = LBFGS(model.parameters(), max_iter=20, tolerance_grad=1e-5, tolerance_change=1e-9)
# optim = LBFGS(model.parameters())
optim_adam = torch.optim.Adam(model.parameters(), lr=0.001)  # Adam优化器

# print(model)
print(get_n_params(model))
n_params = get_n_params(model)

# In[5]:


loss_track = []
N_iter1 = 500
N_iter2 = 500

# 第一阶段：Adam优化100次
for i in tqdm(range(N_iter1)):
    # 清空梯度
    optim_adam.zero_grad()

    # 前向传播计算预测值
    pred_res = model(x_res, t_res)
    pred_left = model(x_left, t_left)
    pred_right = model(x_right, t_right)
    pred_upper = model(x_upper, t_upper)
    pred_lower = model(x_lower, t_lower)

    # 计算梯度（PINN的核心部分）
    u_x = torch.autograd.grad(
        pred_res, x_res,
        grad_outputs=torch.ones_like(pred_res),
        retain_graph=True, create_graph=True
    )[0]
    u_t = torch.autograd.grad(
        pred_res, t_res,
        grad_outputs=torch.ones_like(pred_res),
        retain_graph=True, create_graph=True
    )[0]

    # 计算各项损失
    loss_res = torch.mean((u_t + 50 * u_x) ** 2)  # 残差损失
    loss_bc = torch.mean((pred_upper - pred_lower) ** 2)  # 边界条件损失
    loss_ic = torch.mean((pred_left[:, 0] - torch.sin(x_left[:, 0])) ** 2)  # 初始条件损失

    # 总损失
    total_loss = loss_res + loss_bc + loss_ic

    # 反向传播
    total_loss.backward()

    # 更新参数
    optim_adam.step()

    if i % 20 == 0:
        print(
            'Iter %d, Loss: %.5e, Loss_bc: %.5e, Loss_res: %.5e, Loss_ic: %.5e' % (
                i, total_loss.item(), loss_bc.item(), loss_res.item(), loss_ic.item())
        )

iterss = 0

for i in range(N_iter2):
    def closure():
        global iterss

        pred_res = model(x_res, t_res)
        pred_left = model(x_left, t_left)
        pred_right = model(x_right, t_right)
        pred_upper = model(x_upper, t_upper)
        pred_lower = model(x_lower, t_lower)

        u_x = torch.autograd.grad(pred_res, x_res, grad_outputs=torch.ones_like(pred_res), retain_graph=True,
                                  create_graph=True)[0]
        u_t = torch.autograd.grad(pred_res, t_res, grad_outputs=torch.ones_like(pred_res), retain_graph=True,
                                  create_graph=True)[0]

        loss_res = torch.mean((u_t + 50 * u_x) ** 2)
        loss_bc = torch.mean((pred_upper - pred_lower) ** 2)
        loss_ic = torch.mean((pred_left[:, 0] - torch.sin(x_left[:, 0])) ** 2)

        loss_track.append([loss_res.item(), loss_bc.item(), loss_ic.item()])

        loss = loss_res + loss_bc + loss_ic
        optim.zero_grad()
        loss.backward()

        iterss += 1
        if iterss % 100 == 0:
            print(
                'Iter %d, Loss: %.5e, Loss_bc: %.5e, Loss_res: %.5e, Loss_ic: %.5e' % (
                    iterss, loss.item(), loss_bc.item(), loss_res.item(), loss_ic.item())
            )
        return loss


    optim.step(closure)

# In[6]:


print('Loss Res: {:4f}, Loss_BC: {:4f}, Loss_IC: {:4f}'.format(loss_track[-1][0], loss_track[-1][1], loss_track[-1][2]))
print('Train Loss: {:4f}'.format(np.sum(loss_track[-1])))

# In[7]:


# Visualize PINNsformer
res_test = make_time_sequence(res_test, num_step=NumStep, step=step_len)
res_test = torch.tensor(res_test, dtype=torch.float32, requires_grad=True).to(device)
x_test, t_test = res_test[:, :, 0:1], res_test[:, :, 1:2]

with torch.no_grad():
    pred = model(x_test, t_test)[:, 0:1]
    pred = pred.cpu().detach().numpy()

pred = pred.reshape(101, 101)

mat = scipy.io.loadmat('./convection.mat')
u = mat['u'].reshape(101, 101)

rl1 = np.sum(np.abs(u - pred)) / np.sum(np.abs(u))
rl2 = np.sqrt(np.sum((u - pred) ** 2) / np.sum(u ** 2))

print('relative L1 error: {:4f}'.format(rl1))
print('relative L2 error: {:4f}'.format(rl2))

plt.figure(figsize=(4, 3))
plt.imshow(pred, extent=[0, np.pi * 2, 1, 0], aspect='auto')
plt.xlabel('x')
plt.ylabel('t')
plt.title('Predicted u(x,t)')
plt.colorbar()
plt.tight_layout()
plt.savefig('./convection_pinnsformer_pred.png')
plt.show()

# In[8]:


plt.figure(figsize=(4, 3))
plt.imshow(u, extent=[0, np.pi * 2, 1, 0], aspect='auto')
plt.xlabel('x')
plt.ylabel('t')
plt.title('Exact u(x,t)')
plt.colorbar()
plt.tight_layout()
plt.savefig('./convection_exact.png')
plt.show()

# In[9]:


plt.figure(figsize=(4, 3))
plt.imshow(np.abs(pred - u), extent=[0, np.pi * 2, 1, 0], aspect='auto')
plt.xlabel('x')
plt.ylabel('t')
plt.title('Absolute Error')
plt.colorbar()
plt.tight_layout()
plt.savefig('./convection_pinnsformer_error.png')
plt.show()




`

**Comment by luokuang2001** [comment]
I’ve been working on replicating the results from the paper and have made several attempts, including using different random seeds, starting with Adam followed by L-BFGS, and trying various initializations. However, I’ve still been unable to reproduce the results as described in the paper.

Could you kindly provide a working demo or share the specific code along with the hyperparameters used in your experiments?

My codes are as follows，

[test.txt](https://github.com/user-attachments/files/18652994/test.txt)

**Comment by tsano430** [comment]
I was also unable to reproduce the results for **convection** by changing the random seed or using Adam⇒LBFGS (the reproducible result was for **reaction**). However, when I changed `d_hidden` from 512 to 128, I was able to reproduce the results in my environment with the NVIDIA GeForce RTX 3070. Additionally, I compared (1) LBFGS and (2) Adam⇒LBFGS, and found that (2) produced better results. Thank you. 

![Image](https://github.com/user-attachments/assets/0171e09f-58f1-4b24-a6bc-6882730d5984)

![Image](https://github.com/user-attachments/assets/1d429925-fa1a-4dea-90d9-d0d41a054095)

(1)
```
Train Loss: 0.000057
relative L1 error: 0.024405
relative L2 error: 0.026720
```

(2)
```
Train Loss: 0.000014
relative L1 error: 0.014894
relative L2 error: 0.018163
```

Code
```python
#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import random
from torch.optim import LBFGS
from tqdm import tqdm
import scipy.io

from util import *
from pinn import PINNs
from pinnsformer import PINNsformer

seed = 66
np.random.seed(seed)
random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)

# 检查是否有可用的 GPU
# torch.cuda.init()  # 初始化 CUDA 设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
if torch.cuda.is_available():
    gpu_name = torch.cuda.get_device_name(0)  # 获取第一个 GPU 的名称
    print(f"GPU name: {gpu_name}")
else:
    print("No GPU available.")

# In[3]:
#
N1 = 51
N2 = 51

step_len = 1e-4
NumStep = 5

# Train PINNsformer
res, b_left, b_right, b_upper, b_lower = get_data([0, 2 * np.pi], [0, 1], N1, N2)
res_test, _, _, _, _ = get_data([0, 2 * np.pi], [0, 1], 101, 101)

res = make_time_sequence(res, num_step=NumStep, step=step_len)
b_left = make_time_sequence(b_left, num_step=NumStep, step=step_len)
b_right = make_time_sequence(b_right, num_step=NumStep, step=step_len)
b_upper = make_time_sequence(b_upper, num_step=NumStep, step=step_len)
b_lower = make_time_sequence(b_lower, num_step=NumStep, step=step_len)

res = torch.tensor(res, dtype=torch.float32, requires_grad=True).to(device)
b_left = torch.tensor(b_left, dtype=torch.float32, requires_grad=True).to(device)
b_right = torch.tensor(b_right, dtype=torch.float32, requires_grad=True).to(device)
b_upper = torch.tensor(b_upper, dtype=torch.float32, requires_grad=True).to(device)
b_lower = torch.tensor(b_lower, dtype=torch.float32, requires_grad=True).to(device)

x_res, t_res = res[:, :, 0:1], res[:, :, 1:2]
x_left, t_left = b_left[:, :, 0:1], b_left[:, :, 1:2]
x_right, t_right = b_right[:, :, 0:1], b_right[:, :, 1:2]
x_upper, t_upper = b_upper[:, :, 0:1], b_upper[:, :, 1:2]
x_lower, t_lower = b_lower[:, :, 0:1], b_lower[:, :, 1:2]


def init_weights(m):
    if isinstance(m, nn.Linear):
        torch.nn.init.xavier_uniform_(m.weight)
        # torch.nn.init.normal_(m.weight, mean=0, std=0.1)
        m.bias.data.fill_(0.01)


# In[4]:

# N_iter1 = 0
N_iter1 = 100
N_iter2 = 500

model = PINNsformer(d_out=1, d_hidden=128, d_model=32, N=1, heads=2).to(device)

model.apply(init_weights)
optim = LBFGS(model.parameters(), max_iter=20 * N_iter2, line_search_fn='strong_wolfe')
# optim = LBFGS(model.parameters(), max_iter=20, tolerance_grad=1e-5, tolerance_change=1e-9)
# optim = LBFGS(model.parameters())
optim_adam = torch.optim.Adam(model.parameters(), lr=1e-3)  # Adam优化器

# print(model)
print(get_n_params(model))
n_params = get_n_params(model)

# In[5]:


loss_track = []

# 第一阶段：Adam优化100次
for i in tqdm(range(N_iter1)):
    # 清空梯度
    optim_adam.zero_grad()

    # 前向传播计算预测值
    pred_res = model(x_res, t_res)
    pred_left = model(x_left, t_left)
    pred_right = model(x_right, t_right)
    pred_upper = model(x_upper, t_upper)
    pred_lower = model(x_lower, t_lower)

    # 计算梯度（PINN的核心部分）
    u_x = torch.autograd.grad(
        pred_res, x_res,
        grad_outputs=torch.ones_like(pred_res),
        retain_graph=True, create_graph=True
    )[0]
    u_t = torch.autograd.grad(
        pred_res, t_res,
        grad_outputs=torch.ones_like(pred_res),
        retain_graph=True, create_graph=True
    )[0]

    # 计算各项损失
    loss_res = torch.mean((u_t + 50 * u_x) ** 2)  # 残差损失
    loss_bc = torch.mean((pred_upper - pred_lower) ** 2)  # 边界条件损失
    loss_ic = torch.mean((pred_left[:, 0] - torch.sin(x_left[:, 0])) ** 2)  # 初始条件损失

    # 总损失
    total_loss = loss_res + loss_bc + loss_ic

    # 反向传播
    total_loss.backward()

    # 更新参数
    optim_adam.step()

    if i % 20 == 0:
        print(
            'Iter %d, Loss: %.5e, Loss_bc: %.5e, Loss_res: %.5e, Loss_ic: %.5e' % (
                i, total_loss.item(), loss_bc.item(), loss_res.item(), loss_ic.item())
        )

def closure():
    pred_res = model(x_res, t_res)
    pred_left = model(x_left, t_left)
    pred_right = model(x_right, t_right)
    pred_upper = model(x_upper, t_upper)
    pred_lower = model(x_lower, t_lower)

    u_x = torch.autograd.grad(pred_res, x_res, grad_outputs=torch.ones_like(pred_res), retain_graph=True,
                              create_graph=True)[0]
    u_t = torch.autograd.grad(pred_res, t_res, grad_outputs=torch.ones_like(pred_res), retain_graph=True,
                              create_graph=True)[0]

    loss_res = torch.mean((u_t + 50 * u_x) ** 2)
    loss_bc = torch.mean((pred_upper - pred_lower) ** 2)
    loss_ic = torch.mean((pred_left[:, 0] - torch.sin(x_left[:, 0])) ** 2)

    loss_track.append([loss_res.item(), loss_bc.item(), loss_ic.item()])

    loss = loss_res + loss_bc + loss_ic
    optim.zero_grad()
    loss.backward()
    return loss

optim.step(closure)

# In[6]:


print('Loss Res: {:4f}, Loss_BC: {:4f}, Loss_IC: {:4f}'.format(loss_track[-1][0], loss_track[-1][1], loss_track[-1][2]))
print('Train Loss: {:4f}'.format(np.sum(loss_track[-1])))

# In[7]:


# Visualize PINNsformer
res_test = make_time_sequence(res_test, num_step=NumStep, step=step_len)
res_test = torch.tensor(res_test, dtype=torch.float32, requires_grad=True).to(device)
x_test, t_test = res_test[:, :, 0:1], res_test[:, :, 1:2]

with torch.no_grad():
    pred = model(x_test, t_test)[:, 0:1]
    pred = pred.cpu().detach().numpy()

pred = pred.reshape(101, 101)

mat = scipy.io.loadmat('./convection.mat')
u = mat['u'].reshape(101, 101)

rl1 = np.sum(np.abs(u - pred)) / np.sum(np.abs(u))
rl2 = np.sqrt(np.sum((u - pred) ** 2) / np.sum(u ** 2))

print('relative L1 error: {:4f}'.format(rl1))
print('relative L2 error: {:4f}'.format(rl2))

plt.figure(figsize=(4, 3))
plt.imshow(pred, extent=[0, np.pi * 2, 1, 0], aspect='auto')
plt.xlabel('x')
plt.ylabel('t')
plt.title('Predicted u(x,t)')
plt.colorbar()
plt.tight_layout()
plt.savefig('./convection_pinnsformer_pred.png')
plt.show()

# In[8]:


plt.figure(figsize=(4, 3))
plt.imshow(u, extent=[0, np.pi * 2, 1, 0], aspect='auto')
plt.xlabel('x')
plt.ylabel('t')
plt.title('Exact u(x,t)')
plt.colorbar()
plt.tight_layout()
plt.savefig('./convection_exact.png')
plt.show()

# In[9]:


plt.figure(figsize=(4, 3))
plt.imshow(np.abs(pred - u), extent=[0, np.pi * 2, 1, 0], aspect='auto')
plt.xlabel('x')
plt.ylabel('t')
plt.title('Absolute Error')
plt.colorbar()
plt.tight_layout()
plt.savefig('./convection_pinnsformer_error.png')
plt.show()
```

**Comment by tsano430** [comment]
FYI: https://github.com/AdityaLab/pinnsformer/issues/6#issuecomment-2407857816
